import { createClient } from '@supabase/supabase-js';
import { Resend } from 'resend';

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL || '',
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || ''
);

const resend = new Resend(process.env.RESEND_API_KEY || '');

const PACKAGE_PRICES = {
  preschool: 1200,
  classic: 1800,
  halfday: 2500,
};

export default async function handler(req, res) {
  // CORS headers
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');

  // Handle OPTIONS request for CORS
  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  // Only allow POST
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    console.log('=== CREATE BOOKING API CALLED ===');
    console.log('Received booking data:', JSON.stringify(req.body, null, 2));

    const bookingData = req.body;

    // Validate required fields
    const address = bookingData.full_address || bookingData.address;

    const required = {
      customer_name: bookingData.customer_name,
      organization_name: bookingData.organization_name,
      email: bookingData.email,
      phone: bookingData.phone,
      address: address,
      package_type: bookingData.package_type,
      date: bookingData.date,
      time_slot: bookingData.time_slot,
    };

    const missing = Object.keys(required).filter(key => !required[key]);

    if (missing.length > 0) {
      console.error('Missing required fields:', missing);
      return res.status(400).json({
        error: 'Missing required fields',
        missing: missing
      });
    }

    // Get price for package
    const price = PACKAGE_PRICES[bookingData.package_type] || bookingData.price;

    if (!price) {
      console.error('Invalid package type or missing price:', bookingData.package_type);
      return res.status(400).json({ error: 'Invalid package type or missing price' });
    }

    // Check environment variables
    console.log('Checking environment variables...');
    console.log('Supabase URL exists:', !!process.env.NEXT_PUBLIC_SUPABASE_URL);
    console.log('Supabase Key exists:', !!process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY);
    console.log('Supabase URL length:', process.env.NEXT_PUBLIC_SUPABASE_URL?.length || 0);
    console.log('Supabase Key length:', process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY?.length || 0);

    // Prepare insert data
    const insertData = {
      customer_name: bookingData.customer_name,
      organization_name: bookingData.organization_name,
      email: bookingData.email,
      phone: bookingData.phone,
      full_address: address,
      address_details: bookingData.address_details || null,
      city: bookingData.city || null,
      latitude: bookingData.latitude || null,
      longitude: bookingData.longitude || null,
      package_type: bookingData.package_type,
      date: bookingData.date,
      time_slot: bookingData.time_slot,
      status: 'pending',
      payment_status: 'pending',
      price: price,
      message: bookingData.message || bookingData.special_requests || null,
      special_requests: bookingData.special_requests || bookingData.message || null,
    };

    console.log('Creating booking in Supabase...');
    console.log('Attempting to insert data:', JSON.stringify(insertData, null, 2));

    // Create booking in Supabase - booking_number will be auto-generated by trigger
    const { data: booking, error: dbError } = await supabase
      .from('bookings')
      .insert([insertData])
      .select('id, booking_number, customer_name, organization_name, email, phone, full_address, address_details, city, latitude, longitude, package_type, date, time_slot, status, payment_status, price, message, special_requests')
      .single();

    if (dbError) {
      console.error('=== SUPABASE INSERT FAILED ===');
      console.error('Error object:', dbError);
      console.error('Error code:', dbError.code);
      console.error('Error message:', dbError.message);
      console.error('Error details:', dbError.details);
      console.error('Error hint:', dbError.hint);
      console.error('Full error JSON:', JSON.stringify(dbError, null, 2));

      return res.status(500).json({
        error: 'Failed to create booking in database',
        supabaseError: dbError.message,
        code: dbError.code,
        details: dbError.details,
        hint: dbError.hint,
        insertData: insertData // Include what we tried to insert for debugging
      });
    }

    console.log('Booking created successfully:', booking.id);
    console.log('Booking number:', booking.booking_number);

    // Use booking_number for display, fallback to id if not generated yet
    const displayBookingId = booking.booking_number || booking.id;

    // Send email notifications via Resend
    try {
      const packageNames = {
        preschool: 'Preschool Special (30-45 mins)',
        classic: 'Classic Show (45-60 mins)',
        halfday: 'Half-Day Experience (4 hours)',
      };

      const formattedDate = new Date(bookingData.date).toLocaleDateString('en-US', {
        weekday: 'long',
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      });

      console.log('Sending admin email to carls.newton10@gmail.com...');

      // Send admin notification email
      const adminEmailResult = await resend.emails.send({
        from: 'Carls Newton Bookings <bookings@resend.dev>',
        to: 'carls.newton10@gmail.com',
        subject: `🎯 New Booking #${displayBookingId}: ${bookingData.customer_name} - ${bookingData.organization_name}`,
        html: `
          <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <h2 style="color: #6366f1;">🎉 New Science Show Booked!</h2>

            <div style="background: #dcfce7; padding: 15px; border-radius: 8px; margin-bottom: 20px;">
              <h3 style="margin: 0; color: #166534;">Booking #${displayBookingId}</h3>
            </div>

            <div style="background: #f9fafb; padding: 20px; border-radius: 10px; border-left: 4px solid #6366f1;">
              <h3 style="margin-top: 0; color: #1f2937;">Contact Information</h3>
              <p><strong>Name:</strong> ${bookingData.customer_name}</p>
              <p><strong>Email:</strong> <a href="mailto:${bookingData.email}">${bookingData.email}</a></p>
              <p><strong>Phone:</strong> <a href="tel:${bookingData.phone}">${bookingData.phone}</a></p>
              <p><strong>Organization:</strong> ${bookingData.organization_name}</p>

              <!-- Quick WhatsApp contact button for admin -->
              <div style="margin-top: 15px;">
                <a href="https://wa.me/${bookingData.phone.replace(/[^0-9]/g, '')}?text=Hi%20${encodeURIComponent(bookingData.customer_name)}!%20This%20is%20Carls%20Newton.%20Thank%20you%20for%20booking%20${encodeURIComponent(packageNames[bookingData.package_type])}%20(Booking%20%23${displayBookingId}).%20Let%27s%20confirm%20the%20details!"
                   style="display: inline-block; background: #25D366; color: white; padding: 10px 20px; text-decoration: none; border-radius: 25px; font-size: 14px;">
                  💬 WhatsApp Customer
                </a>
              </div>
            </div>

            <div style="background: #eff6ff; padding: 20px; border-radius: 10px; margin-top: 20px; border-left: 4px solid #3b82f6;">
              <h3 style="margin-top: 0; color: #1f2937;">Event Details</h3>
              <p><strong>Package:</strong> ${packageNames[bookingData.package_type]}</p>
              <p><strong>Price:</strong> AED ${price.toLocaleString()}</p>
              <p><strong>Date:</strong> ${formattedDate}</p>
              <p><strong>Time:</strong> ${bookingData.time_slot}</p>
              <p><strong>Location:</strong> ${address}</p>
              ${bookingData.address_details ? `<p><strong>Details:</strong> ${bookingData.address_details}</p>` : ''}
              ${bookingData.city ? `<p><strong>City:</strong> ${bookingData.city}</p>` : ''}
              ${bookingData.latitude && bookingData.longitude ? `<p><strong>Map:</strong> <a href="https://www.google.com/maps?q=${bookingData.latitude},${bookingData.longitude}" target="_blank">View on Google Maps</a></p>` : ''}
            </div>

            ${(bookingData.special_requests || bookingData.message) ? `
              <div style="background: #fef3c7; padding: 20px; border-radius: 10px; margin-top: 20px; border-left: 4px solid #f59e0b;">
                <h3 style="margin-top: 0; color: #1f2937;">⭐ Special Requests</h3>
                <p style="white-space: pre-wrap;">${bookingData.special_requests || bookingData.message}</p>
              </div>
            ` : ''}

            <div style="margin-top: 30px; padding: 15px; background: #dcfce7; border-radius: 8px;">
              <p style="margin: 0; color: #166534;">
                <strong>Status:</strong> Pending Confirmation<br>
                <strong>Next Step:</strong> Reach out within 24 hours to confirm and discuss payment
              </p>
            </div>

            <p style="margin-top: 20px; color: #6b7280; font-size: 14px;">
              🎯 Booking #${displayBookingId} - Review and contact the customer!
            </p>
          </div>
        `,
      });

      console.log('Admin email sent successfully:', adminEmailResult);

      // Send customer confirmation email
      await resend.emails.send({
        from: 'Carls Newton Bookings <bookings@resend.dev>',
        to: bookingData.email,
        subject: '🎉 Get Ready for an Amazing Science Adventure!',
        html: `
          <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <h1 style="color: #6366f1;">🚀 Woohoo! Your Science Show is Booked!</h1>

            <p style="font-size: 16px; line-height: 1.6;">
              Dear ${bookingData.customer_name},
            </p>

            <p style="font-size: 16px; line-height: 1.6;">
              We're absolutely <strong>thrilled</strong> that you've chosen Carls Newton to bring the magic of science to life!
              Get ready for an experience packed with explosive experiments, mind-blowing discoveries, and lots of "WOW" moments! 🤯✨
            </p>

            <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; border-radius: 10px; margin: 20px 0;">
              <h2 style="margin-top: 0; color: white;">📅 Your Adventure Details</h2>
              <p style="margin: 8px 0;"><strong>Booking Number:</strong> ${displayBookingId}</p>
              <p style="margin: 8px 0;"><strong>Experience:</strong> ${packageNames[bookingData.package_type]}</p>
              <p style="margin: 8px 0;"><strong>Date:</strong> ${formattedDate}</p>
              <p style="margin: 8px 0;"><strong>Time:</strong> ${bookingData.time_slot}</p>
              <p style="margin: 8px 0;"><strong>Location:</strong> ${address}</p>
            </div>

            <!-- WHATSAPP BUTTON -->
            <div style="text-align: center; margin: 30px 0;">
              <a href="https://wa.me/971543771243?text=Hi%20Carls%20Newton!%20I%20just%20booked%20${encodeURIComponent(packageNames[bookingData.package_type])}%20for%20${formattedDate}%20(Booking%20%23${displayBookingId}).%20I%20have%20a%20question!"
                 style="display: inline-block; background: #25D366; color: white; padding: 15px 30px; text-decoration: none; border-radius: 50px; font-weight: bold; font-size: 16px;">
                💬 Chat with us on WhatsApp
              </a>
              <p style="margin-top: 10px; font-size: 14px; color: #666;">
                Quick questions? Message us directly!
              </p>
            </div>

            <h3 style="color: #6366f1;">🎯 What Happens Next?</h3>
            <p style="font-size: 16px; line-height: 1.6;">
              Our team will reach out within 24 hours to confirm details and discuss payment.
              <strong>Prefer WhatsApp?</strong> Click the button above to chat with us instantly! 💬
              We can't wait to spark curiosity and create unforgettable memories with your students! 🔬
            </p>

            ${(bookingData.special_requests || bookingData.message) ? `
              <p style="font-size: 14px; color: #666; background: #f3f4f6; padding: 15px; border-radius: 8px;">
                <strong>Your Special Requests:</strong><br>
                ${bookingData.special_requests || bookingData.message}
              </p>
            ` : ''}

            <p style="font-size: 16px; line-height: 1.6; margin-top: 30px;">
              <strong>Pro tip:</strong> Make sure to have a space ready for the experiments, some curious young minds,
              and maybe a camera to capture those priceless "aha!" moments! 📸
            </p>

            <p style="font-size: 16px; line-height: 1.6;">
              Questions? Excited? Just want to chat about science? Reply to this email or WhatsApp us anytime!
            </p>

            <p style="font-size: 16px; line-height: 1.6; margin-top: 30px;">
              Let's make science FUN! 🎉🧪<br>
              <strong>The Carls Newton Team</strong>
            </p>

            <div style="margin-top: 40px; padding-top: 20px; border-top: 2px solid #e5e7eb; font-size: 12px; color: #6b7280;">
              <p>Carls Newton - Where Science Meets Imagination!</p>
              <p>Booking #${displayBookingId}</p>
              <p>📧 Email: carls.newton10@gmail.com</p>
              <p>💬 WhatsApp: +971 54 377 1243</p>
            </div>
          </div>
        `,
      });

      console.log('Customer email sent successfully');
    } catch (emailError) {
      console.error('Email sending error (non-fatal):', emailError);
      console.error('Email error details:', emailError.message);
      // Don't fail the booking if email fails
    }

    console.log('Booking process completed successfully');
    console.log('Returning booking ID:', displayBookingId);

    return res.status(201).json({
      success: true,
      bookingId: displayBookingId, // Return simplified booking_number
      booking: booking,
      message: 'Booking created successfully',
    });
  } catch (error) {
    console.error('=== FATAL ERROR IN CREATE-BOOKING ===');
    console.error('Error message:', error.message);
    console.error('Error stack:', error.stack);
    console.error('Full error object:', JSON.stringify(error, null, 2));

    return res.status(500).json({
      error: 'Internal server error',
      details: error instanceof Error ? error.message : 'Unknown error',
      stack: process.env.NODE_ENV === 'development' ? error.stack : undefined
    });
  }
}
