import { createClient } from '@supabase/supabase-js';
import { Resend } from 'resend';

// Use service role key for server-side operations (bypasses RLS)
// This is secure because this code only runs on the server, never in the browser
const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL || '',
  process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '',
  {
    auth: {
      autoRefreshToken: false,
      persistSession: false,
      detectSessionInUrl: false
    }
  }
);

const resend = new Resend(process.env.RESEND_API_KEY || '');

const PACKAGE_PRICES = {
  preschool: 1200,
  classic: 1800,
  halfday: 2500,
};

export default async function handler(req, res) {
  // CORS headers
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');

  // Handle OPTIONS request for CORS
  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  // Only allow POST
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    console.log('=== CREATE BOOKING API CALLED ===');
    console.log('Received booking data:', JSON.stringify(req.body, null, 2));

    const bookingData = req.body;

    // Validate required fields
    const address = bookingData.full_address || bookingData.address;

    const required = {
      title: bookingData.title,
      customer_name: bookingData.customer_name,
      job_position: bookingData.job_position,
      organization_name: bookingData.organization_name,
      email: bookingData.email,
      phone: bookingData.phone,
      address: address,
      package_type: bookingData.package_type,
      date: bookingData.date,
      time_slot: bookingData.time_slot,
    };

    const missing = Object.keys(required).filter(key => !required[key]);

    if (missing.length > 0) {
      console.error('Missing required fields:', missing);
      return res.status(400).json({
        error: 'Missing required fields',
        missing: missing
      });
    }

    // Get price for package
    const price = PACKAGE_PRICES[bookingData.package_type] || bookingData.price;

    if (!price) {
      console.error('Invalid package type or missing price:', bookingData.package_type);
      return res.status(400).json({ error: 'Invalid package type or missing price' });
    }

    // Check environment variables
    console.log('Checking environment variables...');
    console.log('Supabase URL exists:', !!process.env.NEXT_PUBLIC_SUPABASE_URL);
    console.log('Supabase Key exists:', !!process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY);
    console.log('Supabase URL length:', process.env.NEXT_PUBLIC_SUPABASE_URL?.length || 0);
    console.log('Supabase Key length:', process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY?.length || 0);

    // Prepare insert data
    const insertData = {
      title: bookingData.title,
      customer_name: bookingData.customer_name,
      job_position: bookingData.job_position,
      organization_name: bookingData.organization_name,
      email: bookingData.email,
      phone: bookingData.phone,
      full_address: address,
      address_details: bookingData.address_details || null,
      city: bookingData.city || null,
      latitude: bookingData.latitude || null,
      longitude: bookingData.longitude || null,
      package_type: bookingData.package_type,
      date: bookingData.date,
      time_slot: bookingData.time_slot,
      status: 'pending',
      payment_status: 'pending',
      price: price,
      message: bookingData.message || bookingData.special_requests || null,
      special_requests: bookingData.special_requests || bookingData.message || null,
    };

    console.log('Creating booking in Supabase...');
    console.log('Attempting to insert data:', JSON.stringify(insertData, null, 2));

    // Create booking in Supabase - booking_number will be auto-generated by trigger (if migration applied)
    const { data: booking, error: dbError } = await supabase
      .from('bookings')
      .insert([insertData])
      .select() // Select all columns to work before and after migration
      .single();

    if (dbError) {
      console.error('=== SUPABASE INSERT FAILED ===');
      console.error('Error object:', dbError);
      console.error('Error code:', dbError.code);
      console.error('Error message:', dbError.message);
      console.error('Error details:', dbError.details);
      console.error('Error hint:', dbError.hint);
      console.error('Full error JSON:', JSON.stringify(dbError, null, 2));

      return res.status(500).json({
        error: 'Failed to create booking in database',
        supabaseError: dbError.message,
        code: dbError.code,
        details: dbError.details,
        hint: dbError.hint,
        insertData: insertData // Include what we tried to insert for debugging
      });
    }

    console.log('Booking created successfully:', booking.id);
    console.log('Booking number:', booking.booking_number || 'not yet generated (migration pending)');

    // Use booking_number for display, fallback to id if migration not applied yet
    const displayBookingId = booking.booking_number || booking.id;
    console.log('Display booking ID:', displayBookingId);

    // Send email notifications via Resend
    const packageNames = {
      preschool: 'Preschool Special (30-45 mins)',
      classic: 'Classic Show (45-60 mins)',
      halfday: 'Half-Day Experience (4 hours)',
    };

    const formattedDate = new Date(bookingData.date).toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });

    // Check Resend API key
    if (!process.env.RESEND_API_KEY) {
      console.error('❌ RESEND_API_KEY is not set!');
      console.error('Warning: Emails will not be sent. Booking created without notification.');
    }

    // Send customer confirmation email first
    try {
      console.log('=== SENDING CUSTOMER EMAIL ===');
      console.log('To:', bookingData.email);
      console.log('Booking Number:', displayBookingId);

      await resend.emails.send({
        from: 'Carls Newton Bookings <bookings@carlsnewton.com>',
        to: bookingData.email,
        subject: '🎉 Get Ready for an Amazing Science Adventure!',
        html: `
          <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <h1 style="color: #6366f1;">🚀 Woohoo! Your Science Show is Booked!</h1>

            <p style="font-size: 16px; line-height: 1.6;">
              Dear ${bookingData.title} ${bookingData.customer_name},
            </p>

            <p style="font-size: 16px; line-height: 1.6;">
              We're absolutely <strong>thrilled</strong> that you've chosen Carls Newton to bring the magic of science to life!
              Get ready for an experience packed with explosive experiments, mind-blowing discoveries, and lots of "WOW" moments! 🤯✨
            </p>

            <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; border-radius: 10px; margin: 20px 0;">
              <h2 style="margin-top: 0; color: white;">📅 Your Adventure Details</h2>
              <p style="margin: 8px 0;"><strong>Booking Number:</strong> ${displayBookingId}</p>
              <p style="margin: 8px 0;"><strong>Experience:</strong> ${packageNames[bookingData.package_type]}</p>
              <p style="margin: 8px 0;"><strong>Date:</strong> ${formattedDate}</p>
              <p style="margin: 8px 0;"><strong>Time:</strong> ${bookingData.time_slot}</p>
              <p style="margin: 8px 0;"><strong>Location:</strong> ${address}</p>
            </div>

            <!-- WHATSAPP BUTTON -->
            <div style="text-align: center; margin: 30px 0;">
              <a href="https://wa.me/971543771243?text=Hi%20Carls%20Newton!%20I%20just%20booked%20${encodeURIComponent(packageNames[bookingData.package_type])}%20for%20${formattedDate}%20(Booking%20%23${displayBookingId}).%20I%20have%20a%20question!"
                 style="display: inline-block; background: #25D366; color: white; padding: 15px 30px; text-decoration: none; border-radius: 50px; font-weight: bold; font-size: 16px;">
                💬 Chat with us on WhatsApp
              </a>
              <p style="margin-top: 10px; font-size: 14px; color: #666;">
                Quick questions? Message us directly!
              </p>
            </div>

            <h3 style="color: #6366f1;">🎯 What Happens Next?</h3>
            <p style="font-size: 16px; line-height: 1.6;">
              Our team will reach out within 24 hours to confirm details and discuss payment.
              <strong>Prefer WhatsApp?</strong> Click the button above to chat with us instantly! 💬
              We can't wait to spark curiosity and create unforgettable memories with your students! 🔬
            </p>

            ${(bookingData.special_requests || bookingData.message) ? `
              <p style="font-size: 14px; color: #666; background: #f3f4f6; padding: 15px; border-radius: 8px;">
                <strong>Your Special Requests:</strong><br>
                ${bookingData.special_requests || bookingData.message}
              </p>
            ` : ''}

            <p style="font-size: 16px; line-height: 1.6; margin-top: 30px;">
              <strong>Pro tip:</strong> Make sure to have a space ready for the experiments, some curious young minds,
              and maybe a camera to capture those priceless "aha!" moments! 📸
            </p>

            <p style="font-size: 16px; line-height: 1.6;">
              Questions? Excited? Just want to chat about science? Reply to this email or WhatsApp us anytime!
            </p>

            <p style="font-size: 16px; line-height: 1.6; margin-top: 30px;">
              Let's make science FUN! 🎉🧪<br>
              <strong>The Carls Newton Team</strong>
            </p>

            <div style="margin-top: 40px; padding-top: 20px; border-top: 2px solid #e5e7eb; font-size: 12px; color: #6b7280;">
              <p>Carls Newton - Where Science Meets Imagination!</p>
              <p>Booking #${displayBookingId}</p>
              <p>📧 Email: carls.newton10@gmail.com</p>
              <p>💬 WhatsApp: +971 54 377 1243</p>
            </div>
          </div>
        `,
      });

      console.log('✅ Customer email sent successfully');
    } catch (customerEmailError) {
      console.error('❌ CUSTOMER EMAIL FAILED:');
      console.error('Error:', customerEmailError);
      console.error('Message:', customerEmailError.message);
      // Log but don't fail the booking
    }

    // Send admin notification email after customer email
    try {
      console.log('=== SENDING ADMIN NOTIFICATION EMAIL ===');
      console.log('To: hello@carlsnewton.com');
      console.log('Booking Number:', displayBookingId);

      const adminEmailResult = await resend.emails.send({
        from: 'Carls Newton <bookings@carlsnewton.com>',
        to: 'hello@carlsnewton.com',
        subject: `New Booking Received - ${bookingData.customer_name} - ${formattedDate}`,
        html: `
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>New Booking Notification</title>
          </head>
          <body style="margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; background-color: #0a0a0a; color: #ffffff;">
            <div style="max-width: 650px; margin: 0 auto; padding: 20px;">

              <!-- Header -->
              <div style="background: linear-gradient(135deg, #d946ef 0%, #06b6d4 100%); padding: 30px; border-radius: 12px 12px 0 0; text-align: center;">
                <h1 style="margin: 0; color: #ffffff; font-size: 28px; font-weight: 700; text-shadow: 0 2px 4px rgba(0,0,0,0.3);">
                  🎯 New Booking Received
                </h1>
                <p style="margin: 10px 0 0 0; color: #ffffff; font-size: 16px; opacity: 0.95;">
                  Booking ID: <strong>${displayBookingId}</strong>
                </p>
              </div>

              <!-- Main Content -->
              <div style="background: #1a1a2e; padding: 30px; border-radius: 0 0 12px 12px;">

                <!-- Customer Details Section -->
                <div style="background: linear-gradient(135deg, #3b0764 0%, #581c87 100%); padding: 20px; border-radius: 10px; margin-bottom: 20px; border-left: 4px solid #d946ef;">
                  <h2 style="margin: 0 0 15px 0; color: #d946ef; font-size: 20px; font-weight: 600;">
                    👤 Customer Details
                  </h2>
                  <table style="width: 100%; border-collapse: collapse;">
                    <tr>
                      <td style="padding: 8px 0; color: #a8a8a8; font-size: 14px; width: 35%;">Full Name:</td>
                      <td style="padding: 8px 0; color: #ffffff; font-size: 14px; font-weight: 500;">${bookingData.title} ${bookingData.customer_name}</td>
                    </tr>
                    ${bookingData.job_position ? `
                    <tr>
                      <td style="padding: 8px 0; color: #a8a8a8; font-size: 14px;">Position:</td>
                      <td style="padding: 8px 0; color: #ffffff; font-size: 14px; font-weight: 500;">${bookingData.job_position}</td>
                    </tr>
                    ` : ''}
                    <tr>
                      <td style="padding: 8px 0; color: #a8a8a8; font-size: 14px;">School/Organization:</td>
                      <td style="padding: 8px 0; color: #ffffff; font-size: 14px; font-weight: 500;">${bookingData.organization_name}</td>
                    </tr>
                    <tr>
                      <td style="padding: 8px 0; color: #a8a8a8; font-size: 14px;">Email:</td>
                      <td style="padding: 8px 0;"><a href="mailto:${bookingData.email}" style="color: #06b6d4; text-decoration: none; font-size: 14px;">${bookingData.email}</a></td>
                    </tr>
                    <tr>
                      <td style="padding: 8px 0; color: #a8a8a8; font-size: 14px;">Phone:</td>
                      <td style="padding: 8px 0;"><a href="tel:${bookingData.phone}" style="color: #06b6d4; text-decoration: none; font-size: 14px;">${bookingData.phone}</a></td>
                    </tr>
                  </table>

                  <!-- WhatsApp Quick Action -->
                  <div style="margin-top: 15px; padding-top: 15px; border-top: 1px solid rgba(255,255,255,0.1);">
                    <a href="https://wa.me/${bookingData.phone.replace(/[^0-9]/g, '')}?text=Hi%20${bookingData.title}%20${encodeURIComponent(bookingData.customer_name)}!%20This%20is%20Carls%20Newton.%20Thank%20you%20for%20booking%20${displayBookingId}.%20Let%27s%20confirm%20your%20details!"
                       style="display: inline-block; background: #25D366; color: #ffffff; padding: 12px 24px; text-decoration: none; border-radius: 8px; font-size: 14px; font-weight: 600; box-shadow: 0 4px 6px rgba(37,211,102,0.3);">
                      💬 Contact via WhatsApp
                    </a>
                  </div>
                </div>

                <!-- Booking Details Section -->
                <div style="background: linear-gradient(135deg, #083344 0%, #164e63 100%); padding: 20px; border-radius: 10px; margin-bottom: 20px; border-left: 4px solid #06b6d4;">
                  <h2 style="margin: 0 0 15px 0; color: #06b6d4; font-size: 20px; font-weight: 600;">
                    📅 Booking Details
                  </h2>
                  <table style="width: 100%; border-collapse: collapse;">
                    <tr>
                      <td style="padding: 8px 0; color: #a8a8a8; font-size: 14px; width: 35%;">Date & Time:</td>
                      <td style="padding: 8px 0; color: #ffffff; font-size: 14px; font-weight: 500;">${formattedDate} at ${bookingData.time_slot}</td>
                    </tr>
                    <tr>
                      <td style="padding: 8px 0; color: #a8a8a8; font-size: 14px;">Package:</td>
                      <td style="padding: 8px 0; color: #ffffff; font-size: 14px; font-weight: 500;">${packageNames[bookingData.package_type]}</td>
                    </tr>
                    <tr>
                      <td style="padding: 8px 0; color: #a8a8a8; font-size: 14px;">Price:</td>
                      <td style="padding: 8px 0; color: #10b981; font-size: 16px; font-weight: 700;">AED ${price.toLocaleString()}</td>
                    </tr>
                    <tr>
                      <td style="padding: 8px 0; color: #a8a8a8; font-size: 14px;">Location:</td>
                      <td style="padding: 8px 0; color: #ffffff; font-size: 14px; font-weight: 500;">${address}</td>
                    </tr>
                    ${bookingData.address_details ? `
                    <tr>
                      <td style="padding: 8px 0; color: #a8a8a8; font-size: 14px;">Address Details:</td>
                      <td style="padding: 8px 0; color: #ffffff; font-size: 14px;">${bookingData.address_details}</td>
                    </tr>
                    ` : ''}
                    ${bookingData.city ? `
                    <tr>
                      <td style="padding: 8px 0; color: #a8a8a8; font-size: 14px;">City:</td>
                      <td style="padding: 8px 0; color: #ffffff; font-size: 14px;">${bookingData.city}</td>
                    </tr>
                    ` : ''}
                  </table>
                </div>

                <!-- Payment Status Section -->
                <div style="background: linear-gradient(135deg, #422006 0%, #78350f 100%); padding: 20px; border-radius: 10px; margin-bottom: 20px; border-left: 4px solid #f59e0b;">
                  <h2 style="margin: 0 0 15px 0; color: #fbbf24; font-size: 20px; font-weight: 600;">
                    💳 Payment Status
                  </h2>
                  <table style="width: 100%; border-collapse: collapse;">
                    <tr>
                      <td style="padding: 8px 0; color: #a8a8a8; font-size: 14px; width: 35%;">Payment Status:</td>
                      <td style="padding: 8px 0;">
                        <span style="background: #fef3c7; color: #92400e; padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: 600; text-transform: uppercase;">
                          Pending
                        </span>
                      </td>
                    </tr>
                    <tr>
                      <td style="padding: 8px 0; color: #a8a8a8; font-size: 14px;">Booking Status:</td>
                      <td style="padding: 8px 0;">
                        <span style="background: #fef3c7; color: #92400e; padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: 600; text-transform: uppercase;">
                          Pending Confirmation
                        </span>
                      </td>
                    </tr>
                    <tr>
                      <td style="padding: 8px 0; color: #a8a8a8; font-size: 14px;">Amount to Collect:</td>
                      <td style="padding: 8px 0; color: #fbbf24; font-size: 16px; font-weight: 700;">AED ${price.toLocaleString()}</td>
                    </tr>
                  </table>
                </div>

                ${(bookingData.special_requests || bookingData.message) ? `
                <!-- Special Requests Section -->
                <div style="background: linear-gradient(135deg, #1e1b4b 0%, #312e81 100%); padding: 20px; border-radius: 10px; margin-bottom: 20px; border-left: 4px solid #8b5cf6;">
                  <h2 style="margin: 0 0 10px 0; color: #a78bfa; font-size: 20px; font-weight: 600;">
                    ⭐ Special Requests / Notes
                  </h2>
                  <p style="margin: 0; color: #e0e0e0; font-size: 14px; line-height: 1.6; white-space: pre-wrap; background: rgba(0,0,0,0.3); padding: 15px; border-radius: 6px;">
                    ${bookingData.special_requests || bookingData.message}
                  </p>
                </div>
                ` : ''}

                <!-- Action Required -->
                <div style="background: linear-gradient(135deg, #14532d 0%, #166534 100%); padding: 20px; border-radius: 10px; text-align: center; border: 2px solid #22c55e;">
                  <h3 style="margin: 0 0 10px 0; color: #22c55e; font-size: 18px; font-weight: 600;">
                    ✅ Next Steps
                  </h3>
                  <p style="margin: 0; color: #dcfce7; font-size: 14px; line-height: 1.6;">
                    Contact the customer within 24 hours to confirm details and arrange payment.
                  </p>
                </div>

              </div>

              <!-- Footer -->
              <div style="text-align: center; padding: 20px; color: #6b7280; font-size: 12px;">
                <p style="margin: 5px 0;">Carls Newton - Science Education Services</p>
                <p style="margin: 5px 0;">This is an automated notification from your booking system</p>
                <p style="margin: 5px 0;">Booking created on ${new Date().toLocaleString('en-US', { timeZone: 'Asia/Dubai' })} GST</p>
              </div>

            </div>
          </body>
          </html>
        `,
      });

      console.log('✅ Admin notification email sent successfully!');
      console.log('Email ID:', adminEmailResult.id);
    } catch (adminEmailError) {
      console.error('❌ ADMIN NOTIFICATION EMAIL FAILED:');
      console.error('Error:', adminEmailError);
      console.error('Message:', adminEmailError.message);
      // Log but don't fail the booking - admin notification failure shouldn't break the booking flow
    }

    console.log('Booking process completed successfully');
    console.log('Returning booking ID:', displayBookingId);

    return res.status(201).json({
      success: true,
      bookingId: displayBookingId, // Return simplified booking_number
      booking: booking,
      message: 'Booking created successfully',
    });
  } catch (error) {
    console.error('=== FATAL ERROR IN CREATE-BOOKING ===');
    console.error('Error message:', error.message);
    console.error('Error stack:', error.stack);
    console.error('Full error object:', JSON.stringify(error, null, 2));

    return res.status(500).json({
      error: 'Internal server error',
      details: error instanceof Error ? error.message : 'Unknown error',
      stack: process.env.NODE_ENV === 'development' ? error.stack : undefined
    });
  }
}
